package com.acme.jrgen;

import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.Map;

/**
 * Helper to populate generated beans from a Map<String, ?>.
 *
 * Keys in the map should match the field names generated by BeanGenerator.
 * Values are converted to String via toString() and passed to the setters.
 */
public final class DataFiller
{
    private DataFiller()
    {
    }

    /**
     * Fill an existing bean instance with values from the map.
     *
     * @param bean   bean instance to fill
     * @param values map of propertyName -> value
     * @return the same bean instance, for chaining
     */
    public static <T> T fillBean(T bean, Map<String, ?> values)
    {
        if (bean == null || values == null)
        {
            return bean;
        }

        Class<?> type = bean.getClass();
        Map<String, Method> setters = new HashMap<>();

        for (Method m : type.getMethods())
        {
            if (!m.getName().startsWith("set"))
            {
                continue;
            }

            if (m.getParameterCount() != 1)
            {
                continue;
            }

            Class<?> pt = m.getParameterTypes()[0];
            // Generated beans use String properties
            if (!String.class.equals(pt))
            {
                continue;
            }

            String propName = decapitalize(m.getName().substring(3));
            setters.put(propName, m);
        }

        for (Map.Entry<String, ?> e : values.entrySet())
        {
            String key = e.getKey();
            Object val = e.getValue();
            if (key == null || val == null)
            {
                continue;
            }

            Method setter = setters.get(key);
            if (setter == null)
            {
                continue;
            }

            try
            {
                setter.invoke(bean, val.toString());
            }
            catch (ReflectiveOperationException ex)
            {
                // Optional: log; for now, silently ignore bad mappings
            }
        }

        return bean;
    }

    /**
     * Convenience: allocate a new bean via default ctor and fill it.
     */
    public static <T> T newAndFill(Class<T> type, Map<String, ?> values)
    {
        try
        {
            T bean = type.getDeclaredConstructor().newInstance();
            return fillBean(bean, values);
        }
        catch (ReflectiveOperationException e)
        {
            throw new IllegalArgumentException("Cannot instantiate bean type: " + type, e);
        }
    }

    private static String decapitalize(String s)
    {
        if (s == null || s.isEmpty())
        {
            return s;
        }

        if (s.length() > 1
            && Character.isUpperCase(s.charAt(0))
            && Character.isUpperCase(s.charAt(1)))
        {
            // e.g., URL -> uRL (keep acronym mostly unchanged)
            return Character.toLowerCase(s.charAt(0)) + s.substring(1);
        }

        return Character.toLowerCase(s.charAt(0)) + s.substring(1);
    }
}
