package com.acme.jrgen;

import java.lang.reflect.Method;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * Helper to populate generated beans from a Map<String, ?>.
 *
 * Keys in the map should match the field names generated by BeanGenerator.
 * Values are converted to the bean's setter parameter type when possible.
 */
public final class DataFiller
{
    private DataFiller()
    {
    }

    /**
     * Fill an existing bean instance with values from the map.
     *
     * @param bean   bean instance to fill
     * @param values map of propertyName -> value
     * @return the same bean instance, for chaining
     */
    public static <T> T fillBean(T bean, Map<String, ?> values)
    {
        if (bean == null || values == null)
        {
            return bean;
        }

        Class<?> type = bean.getClass();
        Map<String, Method> setters = new HashMap<>();

        for (Method m : type.getMethods())
        {
            if (!m.getName().startsWith("set"))
            {
                continue;
            }

            if (m.getParameterCount() != 1)
            {
                continue;
            }

            String propName = decapitalize(m.getName().substring(3));
            setters.put(propName, m);
        }

        for (Map.Entry<String, ?> e : values.entrySet())
        {
            String key = e.getKey();
            Object val = e.getValue();
            if (key == null)
            {
                continue;
            }

            Method setter = setters.get(key);
            if (setter == null)
            {
                continue;
            }

            Class<?> pt = setter.getParameterTypes()[0];
            Object converted = convertValue(val, pt);
            if (converted == null && pt.isPrimitive())
            {
                // can't assign null to primitive; skip
                continue;
            }

            try
            {
                setter.invoke(bean, converted);
            }
            catch (ReflectiveOperationException ex)
            {
                // Optional: log; for now, silently ignore bad mappings
            }
        }

        return bean;
    }

    /**
     * Convenience: allocate a new bean via default ctor and fill it.
     */
    public static <T> T newAndFill(Class<T> type, Map<String, ?> values)
    {
        try
        {
            T bean = type.getDeclaredConstructor().newInstance();
            return fillBean(bean, values);
        }
        catch (ReflectiveOperationException e)
        {
            throw new IllegalArgumentException("Cannot instantiate bean type: " + type, e);
        }
    }

    private static Object convertValue(Object value, Class<?> targetType)
    {
        if (value == null)
        {
            return null;
        }

        if (targetType.isInstance(value))
        {
            return value;
        }

        String s = value.toString();

        if (targetType == String.class)
        {
            return s;
        }

        if (targetType == Double.class || targetType == double.class)
        {
            try
            {
                return Double.valueOf(s);
            }
            catch (NumberFormatException ignored)
            {
                return null;
            }
        }

        if (targetType == Integer.class || targetType == int.class)
        {
            try
            {
                return Integer.valueOf(s);
            }
            catch (NumberFormatException ignored)
            {
                return null;
            }
        }

        if (targetType == Long.class || targetType == long.class)
        {
            try
            {
                return Long.valueOf(s);
            }
            catch (NumberFormatException ignored)
            {
                return null;
            }
        }

        if (targetType == BigDecimal.class)
        {
            try
            {
                return new BigDecimal(s);
            }
            catch (NumberFormatException ignored)
            {
                return null;
            }
        }

        if (targetType == Boolean.class || targetType == boolean.class)
        {
            return Boolean.parseBoolean(s);
        }

        if (targetType == Date.class)
        {
            if (value instanceof Date d)
            {
                return d;
            }
            // You can add parsing from string here if you want
            return null;
        }

        // Fallback: no conversion known
        return null;
    }

    private static String decapitalize(String s)
    {
        if (s == null || s.isEmpty())
        {
            return s;
        }

        if (s.length() > 1
            && Character.isUpperCase(s.charAt(0))
            && Character.isUpperCase(s.charAt(1)))
        {
            // e.g., URL -> uRL (keep acronym mostly unchanged)
            return Character.toLowerCase(s.charAt(0)) + s.substring(1);
        }

        return Character.toLowerCase(s.charAt(0)) + s.substring(1);
    }
}
